logging:
  level:
    .: error
    org.springframework: error
    my.spring.sample: error

spring:
  profiles:
    active: "prod"
  datasource:
    message:
      pre: Start-Database-Configuration
      post: End-Database-Configuration
  cloud:
    message:
      pre: Start-Cloud-Configuration
      post: End-Cloud-Configuration
  main:
    allow-bean-definition-overriding: true # 빈 오버라이딩 허용